### ISSUE TITLE
extend the reference logic

### ISSUE THREAD

**Issue by Flyingmana** [FriendsOfPHP/security-advisories#107]
Hi,
I want to start something similar for the Magento ecosystem. Now we have here not such a composer centric ecosystem which results in projects available over different sources. Some of them even with multiple composer Identifiers.

As other smaller ecosystems may have similar problems, I would like to solve it here to keep a central standard for the format.

My ideas would be to introduce an optional Alias argument, or allowing of multiple reference entries.

How do you see this?

**Comment by fabpot** [comment]
Keeping a central repository (for now) seems like a good idea. Having aliases is also possible. Can you paste here a YAML document that would use such aliases?

**Comment by Flyingmana** [comment]
```yaml
title:     Blind SQL Injection flaw
link:      http://appcheck-ng.com/critical-security-flaw-patched-in-magento-blog-extension-cve-2015-3428/
cve:       CVE-2015-3428
branches:
    1.x:
        time:     2015-05-27 12:00:00
        versions: [<1.3]
reference: composer://connect20/aw_blog
aliases:
    magento://AW/Blog
```
