### ISSUE TITLE
Consider Adopting Package URL

### ISSUE THREAD

**Issue by stevespringett** [FriendsOfPHP/security-advisories#354]
The Package URL (purl) specification defines a "mostly" universal way of describing components regardless of language or ecosystem. Package URL has been adopted by:

- OWASP Dependency-Track
- OWASP Dependency-Check (in progress)
- CycloneDX
- SPDX (in progress)
- SWID (in progress)
- Sonatype OSSIndex

And is being considered by many other vendors as well as NIST.

Package URL support would simply add an additional field to existing advisories. For example:

```yaml
title:     Cross-Site Scripting
link:      https://github.com/erusev/parsedown/pull/495
cve:       CVE-2018-1000162
branches:
    1.x:
        time:     ~
        versions: ['<1.7.0']
reference: composer://erusev/parsedown
purl: pkg:composer/erusev/parsedown
```

Ideally, Package URL would also be supported by security.symfony.com as an alternative to supplying composer.lock. For organizations leveraging BOMs (CycloneDX or SPDX for example) it would be possible for them to simply supply a list of Package URLs and retrieve vulnerability information (similar to OSSIndex). For example, a request containing `pkg:composer/erusev/parsedown@1.6.0` would return the above vulnerability. 

Supporting Package URL in both advisories as well as the Symfony Security service would provide new opportunities for integration - OWASP Dependency-Track for example.
