### ISSUE TITLE
Using exact version constraint without boundaries are faling the validation

### ISSUE THREAD

**Issue by ocramleznem** [FriendsOfPHP/security-advisories#408]
Using the testfile `drupal/drupal/CVE-2019-6342.yaml`

With content:
```yaml
title: Critical - Access bypass
link: https://www.drupal.org/sa-core-2019-008
cve: CVE-2019-6342
branches:
    8.7.x:
        time:     2019-07-16 16:24:00
        versions: ['8.7.4']
reference: composer://drupal/drupal
```

Results in a failing validation:
Run `php.exe -d memory_limit=-1 C:\Users\marco\projects\security-advisories\validator.php`

Output:
```
...
+----------------------------------+------------------------------------------------------------+
| File                             | Issues                                                     |
+----------------------------------+------------------------------------------------------------+
| drupal\drupal\CVE-2019-6342.yaml | Version constraint "8.7.4" is not in an acceptable format. |
|                                  | "versions" must have an upper bound for branch "8.7.x".    |
+----------------------------------+------------------------------------------------------------+`
...
```

IMHO `$isAcceptableVersionConstraint` should allow this kind of version constraint.

Opinions?
